name: Homecoming Kaffeehaus
favicon: null
layout_spectrum: 0.6119733334053308
typography_spectrum: 0.5638061941135675
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4331628470681608
  lightness: 0.12990648299455643
  saturation: 0.7482347444165498
  rhythmicContrast: 0.4426483998540789
purpose: []
